//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:2.0.50727.3074
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Nome file originale:
// Data di generazione: 27/04/2009 16.27.02
namespace QSilver.Web
{
    
    /// <summary>
    /// Nessun commento per QSilverEntities nello schema.
    /// </summary>
    public partial class QSilverEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Inizializza un nuovo oggetto QSilverEntities utilizzando la stringa di connessione trovata nella sezione 'QSilverEntities' del file di configurazione dell'applicazione.
        /// </summary>
        public QSilverEntities() : 
                base("name=QSilverEntities", "QSilverEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inizializzare un nuovo oggetto QSilverEntities.
        /// </summary>
        public QSilverEntities(string connectionString) : 
                base(connectionString, "QSilverEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inizializzare un nuovo oggetto QSilverEntities.
        /// </summary>
        public QSilverEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "QSilverEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Nessun commento per news nello schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<news> news
        {
            get
            {
                if ((this._news == null))
                {
                    this._news = base.CreateQuery<news>("[news]");
                }
                return this._news;
            }
        }
        private global::System.Data.Objects.ObjectQuery<news> _news;
        /// <summary>
        /// Nessun commento per test nello schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<test> test
        {
            get
            {
                if ((this._test == null))
                {
                    this._test = base.CreateQuery<test>("[test]");
                }
                return this._test;
            }
        }
        private global::System.Data.Objects.ObjectQuery<test> _test;
        /// <summary>
        /// Nessun commento per news nello schema.
        /// </summary>
        public void AddTonews(news news)
        {
            base.AddObject("news", news);
        }
        /// <summary>
        /// Nessun commento per test nello schema.
        /// </summary>
        public void AddTotest(test test)
        {
            base.AddObject("test", test);
        }
    }
    /// <summary>
    /// Nessun commento per QSilverModel.news nello schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="QSilverModel", Name="news")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class news : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crea un nuovo oggetto news.
        /// </summary>
        /// <param name="id">Valore iniziale di Id.</param>
        public static news Createnews(int id)
        {
            news news = new news();
            news.Id = id;
            return news;
        }
        /// <summary>
        /// Nessun commento per Property Body nello schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Body
        {
            get
            {
                return this._Body;
            }
            set
            {
                this.OnBodyChanging(value);
                this.ReportPropertyChanging("Body");
                this._Body = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Body");
                this.OnBodyChanged();
            }
        }
        private string _Body;
        partial void OnBodyChanging(string value);
        partial void OnBodyChanged();
        /// <summary>
        /// Nessun commento per Property IconUri nello schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string IconUri
        {
            get
            {
                return this._IconUri;
            }
            set
            {
                this.OnIconUriChanging(value);
                this.ReportPropertyChanging("IconUri");
                this._IconUri = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("IconUri");
                this.OnIconUriChanged();
            }
        }
        private string _IconUri;
        partial void OnIconUriChanging(string value);
        partial void OnIconUriChanged();
        /// <summary>
        /// Nessun commento per Property Id nello schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// Nessun commento per Property Module nello schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Module
        {
            get
            {
                return this._Module;
            }
            set
            {
                this.OnModuleChanging(value);
                this.ReportPropertyChanging("Module");
                this._Module = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Module");
                this.OnModuleChanged();
            }
        }
        private string _Module;
        partial void OnModuleChanging(string value);
        partial void OnModuleChanged();
        /// <summary>
        /// Nessun commento per Property PublishedDate nello schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Nullable<global::System.DateTime> PublishedDate
        {
            get
            {
                return this._PublishedDate;
            }
            set
            {
                this.OnPublishedDateChanging(value);
                this.ReportPropertyChanging("PublishedDate");
                this._PublishedDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("PublishedDate");
                this.OnPublishedDateChanged();
            }
        }
        private global::System.Nullable<global::System.DateTime> _PublishedDate;
        partial void OnPublishedDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnPublishedDateChanged();
        /// <summary>
        /// Nessun commento per Property Title nello schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this.OnTitleChanging(value);
                this.ReportPropertyChanging("Title");
                this._Title = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Title");
                this.OnTitleChanged();
            }
        }
        private string _Title;
        partial void OnTitleChanging(string value);
        partial void OnTitleChanged();
    }
    /// <summary>
    /// Nessun commento per QSilverModel.test nello schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="QSilverModel", Name="test")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class test : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crea un nuovo oggetto test.
        /// </summary>
        /// <param name="id">Valore iniziale di Id.</param>
        public static test Createtest(int id)
        {
            test test = new test();
            test.Id = id;
            return test;
        }
        /// <summary>
        /// Nessun commento per Property Id nello schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// Nessun commento per Property Value nello schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this.ReportPropertyChanging("Value");
                this._Value = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Value");
                this.OnValueChanged();
            }
        }
        private string _Value;
        partial void OnValueChanging(string value);
        partial void OnValueChanged();
    }
}
